[versions]
# Kotlin & Build Tools
kotlin = "2.1.0"
ksp = "2.1.0-1.0.29"
foojay = "0.8.0"

# Libraries
kotlinpoet = "1.16.0"

# Projekt Konfiguration
fpAxioms = "0.0.2"

[libraries]
# KSP API
ksp-api = { group = "com.google.devtools.ksp", name = "symbol-processing-api", version.ref = "ksp" }

# KotlinPoet
kotlinpoet = { group = "com.squareup", name = "kotlinpoet", version.ref = "kotlinpoet" }
kotlinpoet-ksp = { group = "com.squareup", name = "kotlinpoet-ksp", version.ref = "kotlinpoet" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

# Kotlin Stdlib
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
foojay = { id = "org.gradle.toolchains.foojay-resolver-convention", version.ref = "foojay" }

# Das eigene Plugin (zur Referenz im Zielprojekt)
fp-axioms = { id = "org.evoleq.fp-axioms-plugin", version.ref = "fpAxioms" }